### ISSUE TITLE
Suggestion: option to disable overlap for highlights of the same type

### ISSUE THREAD

**Issue by DespairScent** [jltaylor-us/StardewRangeHighlight#4]
That is, the highlight type will be applied only once per cell, instead of “strengthening” its color when two grids of the same type intersect. This will make the highlights look much "cleaner" in some cases.

**Comment by jltaylor-us** [comment]
This is working as intended.  If you want something that works the other way, try Pathoschild's Data Layers mod.

**Comment by jltaylor-us** [comment]
I decided I'd add this as a configurable behavior, after all.
